import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar1 } from "@/components/blocks/shadcnblocks-com-navbar1";
import { DemoOne } from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="dark">
          <Navbar1
            logo={{ url: "/", src: "/parasocial-nobg1.png", alt: "Parasocial", title: "Parasocial" }}
            showLogoTitle={false}
            logoWidthDesktop={220}
            logoWidthMobile={170}
            menu={[
              { title: "Home", url: "/" },
              {
                title: "Services",
                url: "#",
                items: [
                  { title: "Para-Commerce", description: "Where content converts and carts get full", icon: undefined, url: "/Paracommerce" },
                  { title: "Para-Influence", description: "Amplifying voices that matter", icon: undefined, url: "/Parainfluence" },
                  { title: "Para-Studio", description: "Where creativity gets real", icon: undefined, url: "/Parastudio" },
                ],
              },
              { title: "About", url: "/AboutUs" },
              { title: "Contact", url: "/ContactUs" },
            ]}
            mobileExtraLinks={[
              { name: "Press", url: "#" },
              { name: "Contact", url: "/ContactUs" },
            ]}
            auth={{ login: { text: "Log in", url: "#" }, signup: { text: "Sign up", url: "#" } }}
          />
          {children}
          <DemoOne />
        </ThemeProvider>
      </body>
    </html>
  );
}
